version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ssh_logs_db
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: ssh_logs
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  ssh_simulator:
    build: .
    container_name: ssh_simulator
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: your_password
      MYSQL_DATABASE: ssh_logs
    volumes:
      - ./keys:/app/keys
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: 